export const SPLASH_LINES = [
  { top: 'Shape the arc.', accent: 'Out-math the enemy.' },
  { top: 'Commit sine.', accent: 'Cancel cosine.' },
  { top: 'Your parabola is', accent: 'emotionally unavailable.' },
  { top: 'Plot twist:', accent: "it's math." },
  { top: 'Gaslight, gatekeep,', accent: 'graphkeep.' },
  { top: 'They said calc would', accent: 'never matter in space.' },
  { top: "Newton invented this", accent: 'and still lost friends.' },
  { top: "I'm not mad.", accent: "I'm integrally disappointed." },
  { top: 'Peer review denied.', accent: 'Firing anyway.' },
  { top: 'Ask not what your', accent: 'country can sine for you.' },
  { top: 'Error 404:', accent: 'tactically out-mathed.' },
  { top: 'My therapist says', accent: 'stop calling it a duel.' },
  { top: 'Wolfram Alpha', accent: 'could never.' },
  { top: 'Two commanders enter.', accent: 'One goes home quiet.' },
  { top: 'I brought a graphing', accent: 'calculator to a beam fight.' },
  { top: 'Energy low.', accent: 'Self-esteem lower.' },
  { top: 'Move your ship', accent: 'like you mean it (slowly).' },
  { top: 'The bot is', accent: 'also confused.' },
  { top: 'sqrt(-1) of my', accent: 'patience remaining.' },
  { top: 'Click to move.', accent: 'Regret immediately.' },
  { top: 'Press F to', accent: 'pay respects to your fleet.' },
  { top: 'Mathematics is', accent: 'violence with extra steps.' },
  { top: 'We do a little', accent: 'orbital bullying.' },
  { top: "I don't always miss.", accent: "But when I do, it's public." },
  { top: 'Certified', accent: 'function enthusiast.' },
  { top: 'No u-turn.', accent: 'Only u-substitution.' },
  { top: 'The planets are', accent: 'on their side btw.' },
  { top: 'Live, laugh,', accent: 'logarithm.' },
  { top: 'Touch grass?', accent: 'Touch function generator.' },
  { top: 'Skill issue', accent: '(probably the exponent).' },
  { top: 'My winrate is', accent: ' imaginary.' },
  { top: 'Ratio + L +', accent: 'fleet eliminated.' },
  { top: 'Born to plot.', accent: 'Forced to move slowly.' },
  { top: 'Absolute cinema.', accent: 'Relative tragedy.' },
  { top: 'You miss 100%', accent: 'of the shots you sine.' },
  { top: 'No thoughts.', accent: 'Head empty. Need calculator.' },
  { top: 'Main character arc.', accent: 'Side character fleet.' },
  { top: 'POV: you are', accent: 'the asteroid.' },
  { top: 'Tell me you failed calc', accent: 'without telling me.' },
  { top: 'Built different.', accent: 'Aimed different. Missed same.' },
  { top: 'Goated with the sauce.', accent: 'Boated into a planet.' },
  { top: 'What is a ship', accent: 'to a mathematician?' },
  { top: 'Pythagorean theorem', accent: 'could never do this.' },
  { top: 'Euclid walked so', accent: 'we could beam.' },
  { top: 'The limit does not exist.', accent: 'Neither does my fleet.' },
  { top: 'One does not simply', accent: 'walk into Mordor. One sines.' },
  { top: 'May the slope', accent: 'be ever in your favor.' },
  { top: 'You shall not pass', accent: 'said the moon.' },
  { top: 'I am once again', accent: 'asking for energy.' },
  { top: 'This is fine.', accent: 'Everything is on fire.' },
  { top: 'Understandable.', accent: 'Have a nice day (you lost).' },
  { top: 'Skill diff?', accent: 'Graph diff.' },
  { top: 'Get good.', accent: 'Get good at sin.' },
  { top: 'Touching grass is', accent: 'a planet collision hazard.' },
  { top: 'My honest reaction:', accent: 'y = -|x|.' },
  { top: 'No notes.', accent: 'Many notes. All wrong.' },
  { top: 'Instructions unclear.', accent: 'Fleet stuck in planet.' },
  { top: 'Task failed', accent: 'failedly.' },
  { top: 'Speedrun any%', accent: 'fleet destroyed.' },
  { top: '100% completion.', accent: '0% survival rate.' },
  { top: 'Hard mode:', accent: 'remembering the formula.' },
  { top: 'Easy mode:', accent: 'fighting the bot (still hard).' },
  { top: 'Lag?', accent: 'No, just bad.' },
  { top: 'Skill-based matchmaking', accent: 'found someone better at math.' },
  { top: 'Report player', accent: 'for excessive cosine.' },
  { top: 'GG EZ', accent: '(they said, losing).' },
  { top: 'Truly a', accent: 'Spectral Front moment.' },
];

export function pickSplashLine(exclude) {
  if (SPLASH_LINES.length <= 1) return SPLASH_LINES[0];
  let next = SPLASH_LINES[Math.floor(Math.random() * SPLASH_LINES.length)];
  while (next === exclude) next = SPLASH_LINES[Math.floor(Math.random() * SPLASH_LINES.length)];
  return next;
}
