export const SPLASH_LINES = [
  { top: 'Shape the arc.', accent: 'Out-math the enemy.' },
  { top: 'Commit sine.', accent: 'Cancel cosine.' },
  { top: 'Your parabola is', accent: 'emotionally unavailable.' },
  { top: 'Plot twist:', accent: "it's math." },
  { top: 'Gaslight, gatekeep,', accent: 'graphkeep.' },
  { top: 'They said calc would', accent: 'never matter in space.' },
  { top: 'Friendly fire is just', accent: 'aggressive tutoring.' },
  { top: "Newton invented this", accent: 'and still lost friends.' },
  { top: "I'm not mad.", accent: "I'm integrally disappointed." },
  { top: 'Peer review denied.', accent: 'Firing anyway.' },
  { top: 'Ship rotated 90°.', accent: 'So did my ego.' },
  { top: 'This beam is', accent: 'peer-to-peer trauma.' },
  { top: 'Ask not what your', accent: 'country can sine for you.' },
  { top: 'Error 404:', accent: 'tactically out-mathed.' },
  { top: 'My therapist says', accent: 'stop calling it a duel.' },
  { top: 'Wolfram Alpha', accent: 'could never.' },
  { top: 'Two commanders enter.', accent: 'One goes home quiet.' },
  { top: 'I brought a graphing', accent: 'calculator to a beam fight.' },
  { top: 'Energy low.', accent: 'Self-esteem lower.' },
  { top: "That's not a moon.", accent: "That's a collision box." },
  { top: 'Move your ship', accent: 'like you mean it (slowly).' },
  { top: 'The bot is', accent: 'also confused.' },
  { top: 'sqrt(-1) of my', accent: 'patience remaining.' },
  { top: 'Host authoritative.', accent: 'Guest authoritative at crying.' },
  { top: 'Click to move.', accent: 'Regret immediately.' },
  { top: 'Beam exits sector.', accent: 'So does my focus.' },
  { top: 'Range exhausted.', accent: 'Same, honestly.' },
  { top: 'Press F to', accent: 'pay respects to your fleet.' },
  { top: 'Mathematics is', accent: 'violence with extra steps.' },
  { top: 'We do a little', accent: 'orbital bullying.' },
  { top: "I don't always miss.", accent: "But when I do, it's public." },
  { top: 'Certified', accent: 'function enthusiast.' },
  { top: 'The preview line', accent: 'is lying to you lovingly.' },
  { top: 'No u-turn.', accent: 'Only u-substitution.' },
  { top: 'Deploy sigma.', accent: 'Withdraw feelings.' },
  { top: 'Consider the', accent: 'lobster trajectory.' },
  { top: "It's giving", accent: 'quadratic regret.' },
  { top: 'Slurp enemies through', accent: 'a sine wave straw.' },
  { top: 'Be so for real', accent: 'with that slope.' },
  { top: 'Mother said', accent: "it's just ships." },
  { top: 'Real sigma energy is', accent: 'spending 25 energy to move at full burn.' },
  { top: 'The planets are', accent: 'on their side btw.' },
  { top: 'Live, laugh,', accent: 'logarithm.' },
  { top: 'Touch grass?', accent: 'Touch function generator.' },
  { top: 'Skill issue', accent: '(probably the exponent).' },
  { top: 'My winrate is', accent: ' imaginary.' },
  { top: 'Ratio + L +', accent: 'fleet eliminated.' },
  { top: 'Born to plot.', accent: 'Forced to move slowly.' },
  { top: 'Absolute cinema.', accent: 'Relative tragedy.' },
  { top: 'You miss 100%', accent: 'of the shots you sine.' },
  { top: 'Hawk tuah', accent: 'on that trajectory.' },
  { top: 'Very demure.', accent: 'Very tactical.' },
  { top: 'Very mindful.', accent: 'Very out of energy.' },
  { top: 'Delulu is the', accent: 'only solulu (still missed).' },
  { top: 'Brain rot?', accent: 'Brain rotate(ship.angle).' },
  { top: 'No thoughts.', accent: 'Head empty. Need calculator.' },
  { top: 'Main character arc.', accent: 'Side character fleet.' },
  { top: 'Caught in 4K', accent: 'collision resolution.' },
  { top: 'Chat is this', accent: 'real (it is, unfortunately).' },
  { top: 'POV: you are', accent: 'the asteroid.' },
  { top: 'Tell me you failed calc', accent: 'without telling me.' },
  { top: 'Built different.', accent: 'Aimed different. Missed same.' },
  { top: 'Goated with the sauce.', accent: 'Boated into a planet.' },
  { top: 'What is a ship', accent: 'to a mathematician?' },
  { top: 'Pythagorean theorem', accent: 'could never do this.' },
  { top: 'Euclid walked so', accent: 'we could beam.' },
  { top: 'The limit does not exist.', accent: 'Neither does my fleet.' },
  { top: 'One does not simply', accent: 'walk into Mordor. One sines.' },
  { top: 'May the slope', accent: 'be ever in your favor.' },
  { top: 'You shall not pass', accent: 'said the moon.' },
  { top: 'I am once again', accent: 'asking for energy.' },
  { top: 'This is fine.', accent: 'Everything is on fire.' },
  { top: 'Understandable.', accent: 'Have a nice day (you lost).' },
  { top: 'Skill diff?', accent: 'Graph diff.' },
  { top: 'Get good.', accent: 'Get good at sin.' },
  { top: 'Git gud.', accent: 'Git commit sin(x).' },
  { top: 'Touching grass is', accent: 'a planet collision hazard.' },
  { top: 'My honest reaction:', accent: 'y = -|x|.' },
  { top: 'No notes.', accent: 'Many notes. All wrong.' },
  { top: 'She math on my', accent: 'function till I plot.' },
  { top: 'Average calculus fan', accent: 'vs average beam enjoyer.' },
  { top: 'Bottom text', accent: 'Top text (missed anyway).' },
  { top: 'Instructions unclear.', accent: 'Fleet stuck in planet.' },
  { top: 'Task failed', accent: 'failedly.' },
  { top: 'Achievement unlocked:', accent: 'Beam exits sector.' },
  { top: 'Speedrun any%', accent: 'fleet destroyed.' },
  { top: '100% completion.', accent: '0% survival rate.' },
  { top: 'Hard mode:', accent: 'remembering the formula.' },
  { top: 'Easy mode:', accent: 'fighting the bot (still hard).' },
  { top: 'DLC dropped:', accent: 'waypoint movement.' },
  { top: 'Patch notes:', accent: 'removed your turn.' },
  { top: 'Lag?', accent: 'No, just bad.' },
  { top: 'Skill-based matchmaking', accent: 'found someone better at math.' },
  { top: 'Report player', accent: 'for excessive cosine.' },
  { top: 'GG EZ', accent: '(they said, losing).' },
  { top: 'Truly a', accent: 'Spectral Front moment.' },
  { top: 'agagegehehheheheh', accent: 'huehuehuehuehehehh' },
];

export function pickSplashLine(exclude) {
  if (SPLASH_LINES.length <= 1) return SPLASH_LINES[0];
  let next = SPLASH_LINES[Math.floor(Math.random() * SPLASH_LINES.length)];
  while (next === exclude) next = SPLASH_LINES[Math.floor(Math.random() * SPLASH_LINES.length)];
  return next;
}
