'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
const sessionKey = 'spectral-front-session';
const request = async (path, options = {}) => { const r = await fetch(path, { headers: { 'content-type': 'application/json' }, ...options }); const body = await r.json().catch(() => ({})); if (!r.ok) throw Error(body.error || 'Network error'); return body; };
const makeMatch = () => ({ turn: 'host', round: 1, ships: { host: [{x:120,y:150,hp:1},{x:135,y:300,hp:1},{x:120,y:450,hp:1}], guest: [{x:880,y:150,hp:1},{x:865,y:300,hp:1},{x:880,y:450,hp:1}] }, planets: [{x:480,y:185,r:58},{x:570,y:405,r:72}], lastPath: [], outcome: null });
const live = (game, role) => game.ships[role].filter(s => s.hp);

export default function GameClient({ matchId }) {
  const router = useRouter(); const canvas = useRef(null); const peer = useRef(null); const channel = useRef(null); const session = useRef(null); const gameRef = useRef(null);
  const [game, setGame] = useState(null); const [selected, setSelected] = useState(0); const [link, setLink] = useState('LINKING'); const [problem, setProblem] = useState(''); const [formula, setFormula] = useState('0.12 * sin(1.3*x) - 0.04*x'); const [notice, setNotice] = useState('');
  const sync = useCallback(next => { gameRef.current = next; setGame({ ...next, ships: { host: next.ships.host.map(x => ({...x})), guest: next.ships.guest.map(x => ({...x})) }, lastPath: [...next.lastPath] }); }, []);
  const send = useCallback(message => { if (channel.current?.readyState === 'open') channel.current.send(JSON.stringify(message)); }, []);
  const stop = useCallback(() => { channel.current?.close(); peer.current?.close(); }, []);
  const leave = useCallback(async () => { try { await request('/api/signal', { method: 'POST', body: JSON.stringify({ ticket: session.current?.ticket, message: { type: 'peer-left' } }) }); } catch {} stop(); sessionStorage.removeItem(sessionKey); router.push('/'); }, [router, stop]);
  const resolve = useCallback((expression, role, shipIndex) => { const next = gameRef.current; if (!next || next.turn !== role || next.outcome || !next.ships[role][shipIndex]?.hp) return; const path = trace(expression, next.ships[role][shipIndex], role); if (!path.length) { next.turn = role === 'host' ? 'guest' : 'host'; next.round++; setNotice('Unstable function — turn lost.'); send({ type: 'state', state: next }); sync(next); return; } let hit; for (const point of path) { if (next.planets.some(p => Math.hypot(point.x-p.x, point.y-p.y) < p.r)) break; hit = live(next, role === 'host' ? 'guest' : 'host').find(s => Math.hypot(point.x-s.x, point.y-s.y) < 16); if (hit) { hit.hp = 0; break; } } next.lastPath = path; const opponent = role === 'host' ? 'guest' : 'host'; if (!live(next, opponent).length) next.outcome = role; else { next.turn = opponent; next.round++; } setNotice(hit ? 'Direct hit. One ship lost.' : 'Arc dissipated.'); send({ type: 'state', state: next }); sync(next); }, [send, sync]);
  const connect = useCallback(async () => { const stored = JSON.parse(sessionStorage.getItem(sessionKey) || 'null'); if (!stored || stored.matchId !== matchId) { router.replace('/'); return; } session.current = stored; try { const { iceServers } = await request(`/api/ice?ticket=${encodeURIComponent(stored.ticket)}`); const pc = peer.current = new RTCPeerConnection({ iceServers }); pc.onicecandidate = e => e.candidate && request('/api/signal', { method: 'POST', body: JSON.stringify({ ticket: stored.ticket, message: { type: 'candidate', candidate: e.candidate } }) }); pc.onconnectionstatechange = () => { if (['failed','disconnected'].includes(pc.connectionState)) setProblem('Connection lost. The other pilot or their network left the duel.'); }; const open = dc => { channel.current = dc; dc.onopen = () => { setLink('DIRECT LINK'); if (stored.role === 'host') { const created = makeMatch(); send({ type: 'state', state: created }); sync(created); } }; dc.onclose = () => setProblem('The other pilot left the duel.'); dc.onmessage = e => { const message = JSON.parse(e.data); if (message.type === 'state') sync(message.state); if (message.type === 'fire' && stored.role === 'host') resolve(message.expression, 'guest', message.shipIndex); }; }; pc.ondatachannel = e => open(e.channel); if (stored.role === 'host') { open(pc.createDataChannel('match', { ordered: true })); const offer = await pc.createOffer(); await pc.setLocalDescription(offer); await request('/api/signal', { method: 'POST', body: JSON.stringify({ ticket: stored.ticket, message: { type: 'offer', sdp: offer } }) }); } let cancelled = false; (async () => { while (!cancelled && pc.connectionState !== 'closed') { try { const { messages = [] } = await request(`/api/signal?ticket=${encodeURIComponent(stored.ticket)}`); for (const m of messages) { if (m.type === 'offer' && stored.role === 'guest') { await pc.setRemoteDescription(m.sdp); const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); await request('/api/signal', { method: 'POST', body: JSON.stringify({ ticket: stored.ticket, message: { type: 'answer', sdp: answer } }) }); } if (m.type === 'answer' && stored.role === 'host') await pc.setRemoteDescription(m.sdp); if (m.type === 'candidate') await pc.addIceCandidate(m.candidate).catch(() => {}); if (m.type === 'peer-left') setProblem('The other pilot left the duel.'); } } catch {} await new Promise(r => setTimeout(r, 600)); } })(); return () => { cancelled = true; }; } catch (error) { setProblem(error.message); } }, [matchId, resolve, router, send, sync]);
  useEffect(() => { let clean; connect().then(fn => clean = fn); return () => { clean?.(); stop(); }; }, [connect, stop]);
  useEffect(() => { if (!game || !canvas.current) return; const ctx = canvas.current.getContext('2d'), w=1000,h=600; ctx.fillStyle='#07131f';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#183246';for(let x=0;x<w;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const origin=game.ships[session.current.role][selected];if(origin?.hp){ctx.setLineDash([5,6]);ctx.strokeStyle='#5fe2d455';ctx.beginPath();ctx.moveTo(0,origin.y);ctx.lineTo(w,origin.y);ctx.moveTo(origin.x,0);ctx.lineTo(origin.x,h);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#5fe2d4';ctx.beginPath();ctx.arc(origin.x,origin.y,20,0,7);ctx.stroke();ctx.fillStyle='#a7dcd8';ctx.font='10px DM Mono';ctx.fillText('(0, 0)',origin.x+26,origin.y-24)}for(const p of game.planets){const g=ctx.createRadialGradient(p.x-15,p.y-16,4,p.x,p.y,p.r);g.addColorStop(0,'#7694a0');g.addColorStop(1,'#152f42');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();ctx.strokeStyle='#6193a1';ctx.stroke()}if(game.lastPath.length){ctx.strokeStyle='#f0c96a';ctx.lineWidth=3;ctx.beginPath();game.lastPath.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}for(const [role,ships] of Object.entries(game.ships))for(const s of ships){if(!s.hp)continue;ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle=role==='host'?'#5fe2d4':'#f27b82';ctx.beginPath();ctx.moveTo(role==='host'?14:-14,0);ctx.lineTo(role==='host'?-10:10,-8);ctx.lineTo(role==='host'?-5:5,0);ctx.lineTo(role==='host'?-10:10,8);ctx.closePath();ctx.fill();ctx.restore()} }, [game, selected]);
  if (!game || problem) return <div className="game-shell"><header className="game-top"><div className="brand">SPECTRAL <i>FRONT</i></div></header><section className="disconnected standalone"><div>{!problem && <div className="spinner"/>}<h2>{problem ? 'Match unavailable' : 'Setting up the duel'}</h2><p>{problem || 'Securing a direct browser connection…'}</p><button className="primary" onClick={leave}>BACK TO LOBBY</button></div></section></div>;
  const me=session.current.role, foe=me==='host'?'guest':'host', myShips=game.ships[me]; const fire = () => { if (game.turn !== me || !myShips[selected]?.hp) return; if (me === 'host') resolve(formula,'host',selected); else send({type:'fire',expression:formula,shipIndex:selected}); };
  return <div className="game-shell"><header className="game-top"><div className="brand">SPECTRAL <i>FRONT</i></div><div className="match-meta"><span className="online">● {link}</span> &nbsp; MATCH {matchId.slice(0,6).toUpperCase()}</div><button className="leave" onClick={leave}>LEAVE MATCH</button></header><main className="game-grid"><aside className="panel side"><div><div className="label">TURN</div><div className="turn">{game.outcome ? (game.outcome===me?'You won the sector':'Sector lost') : game.turn===me?'Your turn — plot a line':'Rival is plotting'}</div></div><div><div className={'player '+(game.turn===me?'active':'')}><strong>YOUR FLEET</strong><small>SELECT A SHIP</small><div className="ship-select">{myShips.map((ship,i)=><button key={i} disabled={!ship.hp} className={'ship-choice '+(i===selected?'selected':'')} onClick={()=>setSelected(i)}>SHIP {i+1}<i>{ship.hp?'READY':'LOST'}</i></button>)}</div></div><div className={'player enemy '+(game.turn===foe?'active':'')}><strong>RIVAL FLEET</strong><small>OPPOSING FLEET</small><div className="dots">{'● '.repeat(live(game,foe).length)||'—'}</div></div></div><div className="rules">Pick a ship. It is <b>(0,0)</b> for this shot. The field remains Cartesian: left is −x, right is +x, up is +y.</div></aside><section className="panel arena-wrap"><div className="arena-top"><span>LOCAL SIMULATION: <b>{me==='host'?'HOST':'CONNECTED'}</b></span><span>ROUND {String(game.round).padStart(2,'0')}</span></div><canvas ref={canvas} width="1000" height="600"/><div className={'event '+(notice?'show':'')}>{notice}</div><section className="command"><div className="formula"><label>FIRING ARC — Y = F(X)</label><div className="formula-row"><span>y =</span><input value={formula} onChange={e=>setFormula(e.target.value)} autoComplete="off" spellCheck="false"/></div><div className="hint">Origin: selected ship (0, 0) · sin, cos, abs, sqrt, log, exp</div></div><button className="fire" disabled={game.turn!==me||!!game.outcome} onClick={fire}>FIRE ARC</button></section></section></main></div>;
}

function trace(source, ship, role) { let fn; try { fn = compile(source); } catch { return []; } const direction=role==='host'?1:-1, path=[]; for(let i=0;i<520;i++){const x=direction*(i/519)*12,y=fn(x),worldX=ship.x+x*72,worldY=ship.y-y*42;if(!Number.isFinite(y)||Math.abs(y)>30||worldY<0||worldY>600||worldX<0||worldX>1000)break;path.push({x:worldX,y:worldY})}return path; }
function compile(source) { const tokens=source.toLowerCase().match(/\s*(\d*\.?\d+|pi|x|sin|cos|tan|abs|sqrt|log|exp|[()+\-*/^])/g)?.map(x=>x.trim());if(!tokens?.length||tokens.join('')!==source.toLowerCase().replace(/\s/g,''))throw Error();const out=[],ops=[],p={'+':1,'-':1,'*':2,'/':2,'^':3},fn=['sin','cos','tan','abs','sqrt','log','exp'];let expect=true;for(const t of tokens){if(/^\d|^(x|pi)$/.test(t)){out.push(t);expect=false;continue}if(fn.includes(t)){ops.push(t);continue}if(t==='('){ops.push(t);expect=true;continue}if(t===')'){while(ops.length&&ops.at(-1)!=='(')out.push(ops.pop());if(ops.pop()!=='(')throw Error();if(fn.includes(ops.at(-1)))out.push(ops.pop());expect=false;continue}if(t==='-'&&expect)out.push('0');if(!p[t])throw Error();while(ops.length&&p[ops.at(-1)]&&((t==='^'?p[t]<p[ops.at(-1)]:p[t]<=p[ops.at(-1)])))out.push(ops.pop());ops.push(t);expect=true}while(ops.length){const x=ops.pop();if(x==='(')throw Error();out.push(x)}return x=>{const s=[];for(const t of out){if(/^\d/.test(t))s.push(+t);else if(t==='x')s.push(x);else if(t==='pi')s.push(Math.PI);else if(fn.includes(t)){const a=s.pop();s.push(Math[t==='log'?'log':t](a))}else{const b=s.pop(),a=s.pop();s.push(t==='+'?a+b:t==='-'?a-b:t==='*'?a*b:t==='/'?a/b:Math.pow(a,b))}}return s.length===1?s[0]:NaN}; }
